services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Converter\TwigTemplateConverter:
        arguments:
            - '@templating.engine.twig'
            - AppBundle\Mjml\MjmlConverter
